# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.id_account_id import IdAccountId  # noqa: F401,E501
from swagger_server.models.id_comment_id import IdCommentId  # noqa: F401,E501
from swagger_server.models.id_institution_id import IdInstitutionId  # noqa: F401,E501
from swagger_server.models.id_post_id import IdPostId  # noqa: F401,E501
from swagger_server.models.id_tag_id import IdTagId  # noqa: F401,E501
from swagger_server import util


class Post(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: IdPostId=None, author: IdAccountId=None, time: datetime=None, title: str=None, content: str=None, comment: List[IdCommentId]=None, public_post: bool=None, institutes: List[IdInstitutionId]=None, tag_list: List[IdTagId]=None, report_num: int=None, upvote_num: int=None):  # noqa: E501
        """Post - a model defined in Swagger

        :param id: The id of this Post.  # noqa: E501
        :type id: IdPostId
        :param author: The author of this Post.  # noqa: E501
        :type author: IdAccountId
        :param time: The time of this Post.  # noqa: E501
        :type time: datetime
        :param title: The title of this Post.  # noqa: E501
        :type title: str
        :param content: The content of this Post.  # noqa: E501
        :type content: str
        :param comment: The comment of this Post.  # noqa: E501
        :type comment: List[IdCommentId]
        :param public_post: The public_post of this Post.  # noqa: E501
        :type public_post: bool
        :param institutes: The institutes of this Post.  # noqa: E501
        :type institutes: List[IdInstitutionId]
        :param tag_list: The tag_list of this Post.  # noqa: E501
        :type tag_list: List[IdTagId]
        :param report_num: The report_num of this Post.  # noqa: E501
        :type report_num: int
        :param upvote_num: The upvote_num of this Post.  # noqa: E501
        :type upvote_num: int
        """
        self.swagger_types = {
            'id': IdPostId,
            'author': IdAccountId,
            'time': datetime,
            'title': str,
            'content': str,
            'comment': List[IdCommentId],
            'public_post': bool,
            'institutes': List[IdInstitutionId],
            'tag_list': List[IdTagId],
            'report_num': int,
            'upvote_num': int
        }

        self.attribute_map = {
            'id': 'Id',
            'author': 'Author',
            'time': 'Time',
            'title': 'Title',
            'content': 'Content',
            'comment': 'Comment',
            'public_post': 'Public_post',
            'institutes': 'Institutes',
            'tag_list': 'tag_list',
            'report_num': 'Report_num',
            'upvote_num': 'Upvote_num'
        }
        self._id = id
        self._author = author
        self._time = time
        self._title = title
        self._content = content
        self._comment = comment
        self._public_post = public_post
        self._institutes = institutes
        self._tag_list = tag_list
        self._report_num = report_num
        self._upvote_num = upvote_num

    @classmethod
    def from_dict(cls, dikt) -> 'Post':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Post of this Post.  # noqa: E501
        :rtype: Post
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> IdPostId:
        """Gets the id of this Post.


        :return: The id of this Post.
        :rtype: IdPostId
        """
        return self._id

    @id.setter
    def id(self, id: IdPostId):
        """Sets the id of this Post.


        :param id: The id of this Post.
        :type id: IdPostId
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def author(self) -> IdAccountId:
        """Gets the author of this Post.


        :return: The author of this Post.
        :rtype: IdAccountId
        """
        return self._author

    @author.setter
    def author(self, author: IdAccountId):
        """Sets the author of this Post.


        :param author: The author of this Post.
        :type author: IdAccountId
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def time(self) -> datetime:
        """Gets the time of this Post.


        :return: The time of this Post.
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time: datetime):
        """Sets the time of this Post.


        :param time: The time of this Post.
        :type time: datetime
        """
        if time is None:
            raise ValueError("Invalid value for `time`, must not be `None`")  # noqa: E501

        self._time = time

    @property
    def title(self) -> str:
        """Gets the title of this Post.


        :return: The title of this Post.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Post.


        :param title: The title of this Post.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def content(self) -> str:
        """Gets the content of this Post.


        :return: The content of this Post.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this Post.


        :param content: The content of this Post.
        :type content: str
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content

    @property
    def comment(self) -> List[IdCommentId]:
        """Gets the comment of this Post.


        :return: The comment of this Post.
        :rtype: List[IdCommentId]
        """
        return self._comment

    @comment.setter
    def comment(self, comment: List[IdCommentId]):
        """Sets the comment of this Post.


        :param comment: The comment of this Post.
        :type comment: List[IdCommentId]
        """

        self._comment = comment

    @property
    def public_post(self) -> bool:
        """Gets the public_post of this Post.


        :return: The public_post of this Post.
        :rtype: bool
        """
        return self._public_post

    @public_post.setter
    def public_post(self, public_post: bool):
        """Sets the public_post of this Post.


        :param public_post: The public_post of this Post.
        :type public_post: bool
        """
        if public_post is None:
            raise ValueError("Invalid value for `public_post`, must not be `None`")  # noqa: E501

        self._public_post = public_post

    @property
    def institutes(self) -> List[IdInstitutionId]:
        """Gets the institutes of this Post.


        :return: The institutes of this Post.
        :rtype: List[IdInstitutionId]
        """
        return self._institutes

    @institutes.setter
    def institutes(self, institutes: List[IdInstitutionId]):
        """Sets the institutes of this Post.


        :param institutes: The institutes of this Post.
        :type institutes: List[IdInstitutionId]
        """

        self._institutes = institutes

    @property
    def tag_list(self) -> List[IdTagId]:
        """Gets the tag_list of this Post.


        :return: The tag_list of this Post.
        :rtype: List[IdTagId]
        """
        return self._tag_list

    @tag_list.setter
    def tag_list(self, tag_list: List[IdTagId]):
        """Sets the tag_list of this Post.


        :param tag_list: The tag_list of this Post.
        :type tag_list: List[IdTagId]
        """

        self._tag_list = tag_list

    @property
    def report_num(self) -> int:
        """Gets the report_num of this Post.


        :return: The report_num of this Post.
        :rtype: int
        """
        return self._report_num

    @report_num.setter
    def report_num(self, report_num: int):
        """Sets the report_num of this Post.


        :param report_num: The report_num of this Post.
        :type report_num: int
        """
        if report_num is None:
            raise ValueError("Invalid value for `report_num`, must not be `None`")  # noqa: E501

        self._report_num = report_num

    @property
    def upvote_num(self) -> int:
        """Gets the upvote_num of this Post.


        :return: The upvote_num of this Post.
        :rtype: int
        """
        return self._upvote_num

    @upvote_num.setter
    def upvote_num(self, upvote_num: int):
        """Sets the upvote_num of this Post.


        :param upvote_num: The upvote_num of this Post.
        :type upvote_num: int
        """
        if upvote_num is None:
            raise ValueError("Invalid value for `upvote_num`, must not be `None`")  # noqa: E501

        self._upvote_num = upvote_num
